-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE mktstu21_breno.USUARIOS;
DROP TABLE mktstu21_breno.CASA;
DROP TABLE mktstu21_breno.AMBIENTES;
DROP TABLE mktstu21_breno.DETECCOES_MOVIMENTO;
DROP TABLE mktstu21_breno.SOS;

SET FOREIGN_KEY_CHECKS=1;

USE mktstu21_breno;

CREATE TABLE AMBIENTES (
AMB_ID INTEGER AUTO_INCREMENT,
AMB_NOME VARCHAR(100),
AMB_PORTA_ARDUINO VARCHAR(5),
CAS_ID INTEGER,
PRIMARY KEY (AMB_ID)
);

CREATE TABLE SOS (
SOS_ID INTEGER AUTO_INCREMENT,
SOS_MENSAGEM VARCHAR(250),
SOS_CEL2 VARCHAR(20),
SOS_CEL1 VARCHAR(20),
SOS_CEL3 VARCHAR(20),
USU_ID INTEGER,
PRIMARY KEY (SOS_ID)
);

CREATE TABLE DETECCOES_MOVIMENTO (
MOV_ID INTEGER AUTO_INCREMENT,
MOV_ULTIMA_DETECCAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
MOV_VALUE1 VARCHAR(10),
AMB_ID INTEGER,
PRIMARY KEY (MOV_ID),
FOREIGN KEY(AMB_ID) REFERENCES AMBIENTES (AMB_ID)
);

CREATE TABLE CASA (
CAS_ID INTEGER AUTO_INCREMENT,
CAS_SENSOR_LIGADO INTEGER,
CAS_MODO_MONITORAMENTO INTEGER,
USU_ID INTEGER,
PRIMARY KEY (CAS_ID)
);

CREATE TABLE USUARIOS (
USU_ID INTEGER AUTO_INCREMENT,
USU_NOME_USUARIO VARCHAR(50),
USU_NOME VARCHAR(100),
USU_SENHA VARCHAR(50),
USU_SOBRENOME VARCHAR(100),
USU_CELULAR VARCHAR(20),
PRIMARY KEY (USU_ID)
);

ALTER TABLE AMBIENTES ADD FOREIGN KEY(CAS_ID) REFERENCES CASA (CAS_ID);
ALTER TABLE SOS ADD FOREIGN KEY(USU_ID) REFERENCES USUARIOS (USU_ID);
ALTER TABLE CASA ADD FOREIGN KEY(USU_ID) REFERENCES USUARIOS (USU_ID);                 
  