USE mktstu21_breno;

select DETECCOES_MOVIMENTO.MOV_ULTIMA_DETECCAO AS 'ÚLTIMA DETECÇÃO', AMBIENTES.AMB_NOME AS 'NOME AMBIENTE', AMBIENTES.AMB_PORTA_ARDUINO AS 'PORTA SENSOR' 
from DETECCOES_MOVIMENTO, AMBIENTES 
where DETECCOES_MOVIMENTO.AMB_ID = AMBIENTES.AMB_PORTA_ARDUINO;

select CAS_SENSOR_LIGADO AS 'SENSOR LIGADO' from CASA;

SELECT * FROM DETECCOES_MOVIMENTO;
SELECT * FROM CASA;
SELECT * FROM AMBIENTES;
SELECT * FROM USUARIOS;

SELECT CAS_SENSOR_LIGADO FROM CASA;

INSERT INTO CASA VALUES (1, 1, 1, 4);
INSERT INTO AMBIENTES VALUES (2, 'Sala', '2', 1);
INSERT INTO AMBIENTES VALUES (3, 'Varanda', '34', 1);

UPDATE CASA SET CAS_SENSOR_LIGADO = 0 WHERE CAS_ID = 1;

SELECT CAS_SENSOR_LIGADO FROM CASA;

SELECT * FROM mktstu21_breno.CASA;
UPDATE `mktstu21_breno`.`CASA` SET `CAS_SENSOR_LIGADO` = '1' WHERE (`CAS_ID` = '1') and (`USU_ID` = '4');
